language: rust
rust:
  - nightly-2020-10-30
  - nightly
stages:
  - ensure format
  - deny warnings
  - test
script:
  - export RUST_TARGET_PATH=$PWD
  - cargo +$TRAVIS_RUST_VERSION build
jobs:
  include:
    - stage: ensure format
      if: branch = develop
      script:
        - rustup toolchain install nightly --profile minimal --component rustfmt
        - cargo +nightly fmt -- --check
    - stage: deny warnings
      if: branch = develop
      script:
        - rustup toolchain install nightly --profile minimal --component clippy
        - export RUST_TARGET_PATH=$PWD
        - RUSTFLAGS='-D warnings' cargo +nightly build --all-targets
  fast_finish: true
cache: cargo
